### ISSUE TITLE
Update Tag Status for Dead Sapling/Tree Status (Data)

### ISSUE THREAD

**Issue by blcampbell** [NCRN/ForestVeg#1]
When saplings are given the status of "Dead" the application should also update the tag status to "Retired In Office" 

- Run queries to check for all existing "Dead" statuses which do not have "Retired In Office" (RIO) or "Inactive/Lost" (IL) tag statuses
- Set records returned from queries which do not have RIO or IL statuses to RIO
- Update application to add a trigger setting Tag status when "Dead" status is set

**Comment by blcampbell** [comment]
@lizmatthews03 
Confirming records whose tag statuses should be set to RIO... **[Questions below...]**

**Dead Statuses Included**

- Dead
- Dead - Human Action
- Dead - Too Small
- Dead Fallen
- Dead Leaning
- Dead Missing
- Dead Standing

**Trees**

- 3208 "Dead" trees
- 6 "Dead" trees w/ tag status = RIO
- 3202 "Dead" trees w/ tag statuses <> RIO

**Saplings**

- 1371 "Dead" saplings
- 1194 "Dead" saplings w/ tag status = RIO
- 177 "Dead" saplings w/ tag statuses <> RIO

**Questions**
1. **_Should any of the "Dead" statuses be excluded from the list of those whose tag status should be set to RIO?_**
2. _**Do the 3202 "Dead" trees and 177 "Dead" saplings numbers mesh with expected numbers needing to be updated to RIO?**_

**Comment by blcampbell** [comment]
Per discussion w/ @johnpauls  RIO scripts require filtering as a list of "Inactive" tags which needs to be reviewed as well.
 
Deferring this issue until the "inactives" are cross-referenced.

Separating out the application trigger portion of this issue to a new issue (#23)  & revising this issue's naming to reflect it's data focus.

**Comment by blcampbell** [comment]
Per discussion w/ @johnpauls & @lizmatthews03 

- Identify the 177 "Dead" saplings w/ tag statusess <> RIO (attach csv w/ tag status only)
- Update 177 "Dead" saplings w/ tag statuses <> RIO to RIO

Trees should not be updated.
Sapling tag statuses which should not be RIO w/in this group of 177 should be individually (manually) checked.

**Comment by johnpauls** [comment]
Based on a quick look there are a bunch of these that are not in the office.
