### ISSUE TITLE
Add tree/sapling/shrub condition for stress related to vines.

### ISSUE THREAD

**Issue by lizmatthews03** [NCRN/ForestVeg#111]
This was discussed during the 2018 operational review. Seems like a good idea to me. If we can add it for this year (2019) great, otherwise we'll defer to 2020. 

After the condition is added to Db, we will also need to update protocol to define this condition.

**Comment by blcampbell** [comment]
'Vine stress' condition added with 'tree/sapling/shrub stress due to vine(s)' description.
