### ISSUE TITLE
"minimum 1.0 sapling DBH" popping-up frequently

### ISSUE THREAD

**Issue by abrolis** [NCRN/ForestVeg#122]
Joe says "It happens after inputting the DBH and then it usually happens a second time when you go through the VCF options.  I think it still happens after you click the double check the DBH box."

**Comment by lizmatthews03** [comment]
To clarify, this pop-up comes up for every sapling. If we can't fix it, let's disable it.

**Comment by abrolis** [comment]
Ideally the sapling DBH pop-up would be there so that we know we actually did double check the DBH of a sapling that grew or shrank too much.  

Nick says "The issue is the DBH warning pop-up often pops up when there is no issue, saying “saplings must be at least 1 cm” after we had entered a DBH that was far greater than 1 cm. We dismissed the sapling DBH popup all season because it wasn’t functioning properly and checked off the double check automatically. But there were saplings that may have needed a double check that were flagged in QA/QC (see example below).

Example: CATO-0037 has a sapling (22244) with a DBH of 2.4 cm on a single stem in 2015 sampling and a DBH of 8.4 cm on three stems (7, 1.8, 3.9) in 2019. "

**Comment by blcampbell** [comment]
Popup for every sapling should be resolved, however in some instances the stems DBH value doesn't update before the check resulting in an invalid DBH popup.

![image](https://user-images.githubusercontent.com/36767405/86074839-b252a000-ba54-11ea-8dc0-370a9de4be80.png)

![image](https://user-images.githubusercontent.com/36767405/86075613-6b65aa00-ba56-11ea-8d3b-4fe48a62ce9f.png)

**Comment by blcampbell** [comment]
Added a function (check) that tests for Equiv DBH _before_ the DBH check that triggers popups.

**Result** 
Even though the subform doesn't update L/D to 8.39 _(example above)_ before the DBH check the new function retrieves the actual value and does not allow the check to proceed unless the value is < 1.

**Important**
Need test cases to check that this fix still allows the popup to proceed when it should - including tests in the field.
