### ISSUE TITLE
When looking at the Event report, for saplings, we do not see the VCF checkboxes

### ISSUE THREAD

**Issue by abrolis** [NCRN/ForestVeg#157]
It would be helpful during review to make sure all data was collected for each individual.
Adding these check boxes so they show up on the event reports would enable us to know for sure whether we completed the Vines, Conditions, and Foliar issues for each sapling.

**Comment by blcampbell** [comment]
Sapling V-C-F checkbox data added.

![image](https://user-images.githubusercontent.com/36767405/86046059-8fa39580-ba1a-11ea-9159-bdf31f2b29e4.png)

Highlights red under the VCF when any of the V-C-F checks are not checked.
