### ISSUE TITLE
Allow for herbaceous species to be recorded in dB without % cover or browse

### ISSUE THREAD

**Issue by abrolis** [NCRN/ForestVeg#176]
After selecting a targeted herbaceous species the dB is requiring that % cover and browse are recorded before moving on to next species. 

-Ideally we could record species without adding this information immediately.  It helps with work flow in the field  
-Perhaps use -999 as default value and figure out how to deal with not recording browse

**Comment by blcampbell** [comment]
As currently implemented the value -999 is set as a default to allow users to select the species only and move onto the next record, however the display clearly notes the missing data

![image](https://user-images.githubusercontent.com/36767405/86001977-ac6da800-b9dd-11ea-949f-08e98470a5b4.png)

Any value < 0 displays with yellow background and red text, but does not prevent entry of the record.
 
This does mean that -999 values can make it into the % cover field, so these should be noted in the event report and possibly the R QC checks.
