### ISSUE TITLE
Remove “retired in office” tags from unsampled tags and event report

### ISSUE THREAD

**Issue by abrolis** [NCRN/ForestVeg#178]
With all of our retired Lindera, Kalmia, and sometimes Acer negundo we have many extra pages (e.g CHOH 1045, 10 pages of retired tags)  

-Reorganize active tags at top and move removed from study, inactive in field, missing (missing in two consecutive cycles) and retired in office to the bottom of the list
-Remove all RIO tags from dB dropdowns

**Comment by blcampbell** [comment]
Revised SQL query to re-order Event Report unsampled tag display.

Moves these statuses to the bottom of the list in the report
- Retired (In Office)
- Inactive (In Field)
- Inactive (Lost)

Split off #185 for drop-down list adjustments which are separate from the Event Report adjustment.
