### ISSUE TITLE
Make sure plot NACE-0490 is available

### ISSUE THREAD

**Issue by johnpauls** [NCRN/ForestVeg#19]
Plot NACE-0490  in Piscataway was monitored in 2006, not monitored in 2010 and 2014 and will be picked up again in 2018. In should be in the GPS for the crew and available in the field database as a plot you can chose to monitor.

**Comment by blcampbell** [comment]
@johnpauls , @lizmatthews03 

Looks like NACE-0490 is active, but is on panel 1 vs. 4 which causes it to filter out of the dropdown.

Which panel should it be on?

**Comment by johnpauls** [comment]
Panel 1 is correct.

**Comment by lizmatthews03** [comment]
It should be part of Panel 1. Not sure why we missed it yesterday....

-----------------------------
Liz Matthews, PhD
Botanist
National Capital Region Network
Inventory and Monitoring
National Park Service
*https://www.nps.gov/im/ncrn/index.htm
<https://www.nps.gov/im/ncrn/index.htm>*
email: elizabeth_matthews@nps.gov
office: 202-339-8303
cell: 828-337-2946

**Comment by blcampbell** [comment]
Ensured tsys_App_Defaults are set to panel 1 (2018)
