### ISSUE TITLE
Prior DBH's in event report are not showing the correct data

### ISSUE THREAD

**Issue by abrolis** [NCRN/ForestVeg#197]
The "prior DBH" in the event report aren't showing the actual DBHs from the previous monitoring. It appears to be showing values similar to the DBHs measured that day, perhaps rounded numbers from equivalent DBH. 

This does seem like it would be a helpful feature if it showed the correct data.

**Comment by blcampbell** [comment]
The "Prior DBH" feature was added to provide insight into the prior DBH value for comparison.  It was not designed to specify DBH values for each measured stem and provides only the simple sum of DBH values (rounded to 2 decimals) for the last sampling event where the tag was monitored. In many cases this value _is_ similar to the current event's Equivalent DBH.  The design highlights those prior DBH values > +/- 4 cm different from the current sampling Equivalent DBH.

See #204 for addition of prior sampling event individual stem DBH values.
