### ISSUE TITLE
Add Parthenocissus tricupsidata to database

### ISSUE THREAD

**Issue by johnpauls** [NCRN/ForestVeg#219]
This is a new species of exotic vine that was found for the first time in Rock Creek in 2020 in plot ROCR-0079, on tree 16815. This species was not in the list of species in the database. 2 things need to be done:

1) Add this species to the list of plants in the database
2) Then go back to the Rock Creek data and select the correct species for this vine.

**Comment by blcampbell** [comment]
After lookups to ITIS, USDA Plants & NPSpecies, the following is what would be entered for this species


TSN | 28604
TSN_Accepted | 28604
PLANTS_Code | PATR6
Order | Vitales
Family | Vitaceae
Genus | Parthenocissus
Species | Parthenocissus   tricuspidata
Subspecies |  
Latin_Name | Parthenocissus tricuspidata
Rank_Name | Species
Common | Boston ivy
Favorite | 0
Woody | 0
Herbaceous | 0
Targeted_Herb | 0
Tree | 0
Vine | 1
Exotic | 1
Sensitive | 0
NPSpecies_Common | Boston ivy
Accepted_Found |  
Taxon_Code | 124838

**Please confirm** 
(1) that this data (_above_) is what is desired for this species 
and
(2) whether the record for its synonym - _Ampelopsis tricuspidata_ - should be added with its TSN_Accepted pointing to the _Parthenocissus   tricuspidata_ TSN (i.e. _Ampelopsis tricuspidata_ observations will point to _Parthenocissus tricuspidata_).

**Comment by blcampbell** [comment]
_Parthenocissus tricuspidata_ has been updated to reflect the above changes with these exceptions:

- Order of the existing record was changed from _Rhamnales_ to _Vitales_ per ITIS record (USDA Plants uses _Rhamnales_)
- Woody flag is set to True

**IF** updates to this plant record are required 
**OR** 
there is a desire to add a record for it's synonym _Ampelopsis tricuspidata_ per the 1/21/2021 confirmation request above, **please create a new issue referencing this one.**
