### ISSUE TITLE
Browse observations on Saplings

### ISSUE THREAD

**Issue by lizmatthews03** [NCRN/ForestVeg#33]
Db won't allow input of browse data on saplings and shrubs. For the first few plots, this information was captured in the notes for each sapling/shrub tag.

**Comment by blcampbell** [comment]
Related to #43 .

Changing this to ensure first few plot data is properly set for this field.

Was there a typical note text that was added?

**Comment by lizmatthews03** [comment]
The note varied by tag number.  Since this only affects a few plots/sapling tags at this point, I think we should simply move this data by hand when the browsable/browsed drop-down is working.

**Comment by blcampbell** [comment]
Saplings edited via user interface for the following (comment removed & browseable/browsed set)

![image](https://user-images.githubusercontent.com/36767405/39459084-fbaabe0c-4cc6-11e8-8704-974524d4d70c.png)

Unchecked items had no comment so browseable/browsed remains unset.

GWMP-0314 4/23/2018 browseable/browsed set when field notes addressed.
