### ISSUE TITLE
Retired in office tree tags

### ISSUE THREAD

**Issue by lizmatthews03** [NCRN/ForestVeg#39]
Trees that were "dead standing" or "dead leaning" at the last sample are showing up as "retired in office" in the drop-down pick list. These should still be active tree tags.

Only trees recorded as "dead fallen" become "retired in office".

**Comment by johnpauls** [comment]
I think "dead fallen' should be recorded as "retired in field" as they are kept with the fallen tree.

**Comment by lizmatthews03** [comment]
Or should they be "inactive in field"?

-----------------------------
Liz Matthews, PhD
Botanist
National Capital Region Network
Inventory and Monitoring
National Park Service
*https://www.nps.gov/im/ncrn/index.htm
<https://www.nps.gov/im/ncrn/index.htm>*
email: elizabeth_matthews@nps.gov
office: 202-339-8303
cell: 828-337-2946

**Comment by johnpauls** [comment]
Yes, "inactive in field" is correct.

**Comment by lizmatthews03** [comment]
I know there were a few examples of this issue from Friday's plots. I can't
seem to access the 2018 version of the Db (found here:
T:\I&M\MONITORING\Forest_Vegetation\Database\2018 Forest Veg\NCRN ForestVeg
Database\ForestVeg_2018) from my laptop, so it's hard to pin point
examples.

Using the 2017 Db (here: T:\I&M\MONITORING\Forest_Vegetation\Database\2017
Forest Veg), I can see that Tree tag #12522 was recorded as dead standing
in 2014. In this version of the Db the tag status is "Tree". Assuming this
is one of the trees that showed up as RIO on Friday (which I *think *is the
case), it's tag status must have been updated in one of the queries run...

~Liz



-----------------------------
Liz Matthews, PhD
Botanist
National Capital Region Network
Inventory and Monitoring
National Park Service
*https://www.nps.gov/im/ncrn/index.htm
<https://www.nps.gov/im/ncrn/index.htm>*
email: elizabeth_matthews@nps.gov
office: 202-339-8303
cell: 828-337-2946

**Comment by lizmatthews03** [comment]
Same story for Tree tag #20961. Both tags were in NACE-0004

-----------------------------
Liz Matthews, PhD
Botanist
National Capital Region Network
Inventory and Monitoring
National Park Service
*https://www.nps.gov/im/ncrn/index.htm
<https://www.nps.gov/im/ncrn/index.htm>*
email: elizabeth_matthews@nps.gov
office: 202-339-8303
cell: 828-337-2946

**Comment by blcampbell** [comment]
Trees with the following Tree Statuses now have Tag Statuses as below.
_Number of changed records is listed in italics._

- Tree
-- Dead Leaning _108_
-- Dead Standing _1645_
-- Dead Missing _16_
-- Dead - Human Action _3_
- Inactive (In Field)
-- Dead Fallen _575_
-- Dead - Too Small _27_

Tag Statuses for various Tree Statuses per verbal discussion 4/30/2018.
