### ISSUE TITLE
Unsampled quadrats do not show up on Event Report

### ISSUE THREAD

**Issue by lizmatthews03** [NCRN/ForestVeg#40]
If a quadrat is completed overlooked and unsampled, it does not show up on the Event Report. 

Unsampled quadrats and/or categories within a quadrat (e.g., "herbs" or "grasses") should show up in red on the Event Report.

**Comment by johnpauls** [comment]
I think the quadrat should appear with the rest of the quadrats on the report, except that all of the data is missing and highlighted red. I don't know if this is new.

**Comment by lizmatthews03** [comment]
Yep, exactly as JP described. Also not sure if this is new or not...in the
past, if a single field was skipped in the quadrat, it showed up
highlighted in red...but now that I think about it, it may be that quadrats
that were completely skipped didn't show up in red....

-----------------------------
Liz Matthews, PhD
Botanist
National Capital Region Network
Inventory and Monitoring
National Park Service
*https://www.nps.gov/im/ncrn/index.htm
<https://www.nps.gov/im/ncrn/index.htm>*
email: elizabeth_matthews@nps.gov
office: 202-339-8303
cell: 828-337-2946
