### ISSUE TITLE
Species Pad - Allow Double Click Selection

### ISSUE THREAD

**Issue by blcampbell** [NCRN/ForestVeg#44]
Species pad allows users to select species, but a double-click would be faster thank clicking the arrow to select and dismiss the dialog box.

**Comment by abrolis** [comment]
Not sure if  this would work well in the field.  The chance for someone to accidentally choose the wrong species outweighs the benefit of increase in speed.  Also, with the problems that we have with the stylus and the cursor not lining up makes me think that errors would likely happen on a regular basis.
