### ISSUE TITLE
Tree name has trailing space

### ISSUE THREAD

**Issue by johnpauls** [NCRN/ForestVeg#48]
Tree 16444 from NACE-0350 is "Malus floribunda "   with a trailing space. This record should be corrected and I don't know if that would recur if someone chose that species again. 

I am listing this as critical solely because the visualizer chokes on this (can't match with common name) but I could fix this in the export file as a stop gap if needed.

**Comment by blcampbell** [comment]
111 Latin names in tlu_Plants contained trailing spaces

When these are resolved (in upcoming back-end update) the issue should be resolved for future exports & reporting from the database.
