### ISSUE TITLE
Highlight Live DBH recorded for Dead Trees on event report

### ISSUE THREAD

**Issue by lizmatthews03** [NCRN/ForestVeg#49]
For dead trees, any DBH values recorded as "live" should be highlighted in red on the Event Report. 

It's possible that some dead trees will have living stems (and hence some live DBH), but all dead trees should have at least one dead stem measuring at least 10cm. This highlighting will bring the reviewer's attention to dead trees with live DBH and have them confirm it was recorded correctly.

**Comment by blcampbell** [comment]
Updated version appears thus:

![image](https://user-images.githubusercontent.com/36767405/40001767-e8dfc3c6-575c-11e8-8e91-f89f656d0fa7.png)

_Above report test sample also shows missing distance._

Catches 2 scenarios (_highlights both DBH and Tree Status_):

- Tree Status = Dead *  with **Alive** DBHs
- Tree Status = Alive *   with **no Alive** DBHs

Dead * = Dead (Standing/Leaning/Fallen/Missing)
Alive * = Alive (Standing/Leaning/Broken/Fallen)
