### ISSUE TITLE
Event Report - Limit Red Highlights to Actual Issues

### ISSUE THREAD

**Issue by blcampbell** [NCRN/ForestVeg#5]
Reduce # of reds to improve efficiency.

Don't flag items which are ok - e.g. no DBH for dead trees.

**Comment by blcampbell** [comment]
@lizmatthews03, @johnpauls:  
By chance do you have a list of "don't" or "do" flag for this one  (whichever is more brief)?

**Comment by lizmatthews03** [comment]
Areas that currently show up in red on the print out (but shouldn't) include:
- for dead trees, missing DBH, crown class, V-C-F, and vigor are all highlighted red. None of these fields are required for dead trees (accept for Condition - emerald ash borer on some dead ash trees, as appropriate)
-for dead saplings, browsable/browsed and habit show up in red (neither field is required for dead saplings)
-for shrubs with a removed from study or dead status, browsable/browsed and habit show up in red and should not

I'm trying to think if there is anything that SHOULD be flagged, but which currently doesn't show up as flagged...nothing is coming to mind, but I'll add another comment if I come up with one...

**Comment by johnpauls** [comment]
Clarification - for dead standing or dead leaning trees, dbh is still required.  Trees that are dead fallen or dead - too small do not require any data at all (but folks could add notes or check EAB is they wish).

**Comment by lizmatthews03** [comment]
Identified two errors that **don't** currently show up in red on the Event Report, but which SHOULD:

-  missing species IDs for seedlings (in quadrats)

- saplings whose equivalent DBH is greater than or equal to 10cm (ideally, these should be upgraded to trees, and the appropriate data taken while in the field)

**Comment by blcampbell** [comment]
Confirm "dead trees" _(see @lizmatthews03  comment 11 days ago) includes_ _**all**_ dead categories correct?

Here's the current list of tree status categories (dead categories highlighted):
![image](https://user-images.githubusercontent.com/36767405/38198878-852fd3f0-365c-11e8-9cdd-160cdf02c247.png)

**Comment by johnpauls** [comment]
Related to this - none of the downgraded, missing or removed from study trees should have any data, except for their change in status and some notes to go along with it. Not sure how the printout currently treats these.

**Comment by lizmatthews03** [comment]
Correct!

-----------------------------
Liz Matthews, PhD
Botanist
National Capital Region Network
Inventory and Monitoring
National Park Service
*https://www.nps.gov/im/ncrn/index.htm
<https://www.nps.gov/im/ncrn/index.htm>*
email: elizabeth_matthews@nps.gov
office: 202-339-8303
cell: 828-337-2946
