### ISSUE TITLE
Downgraded trees on the Event Report should be treated the same way as Dead Fallen

### ISSUE THREAD

**Issue by lizmatthews03** [NCRN/ForestVeg#51]
Currently, all of the empty field associated with Downgraded to Non-Sampled trees show up highlighted in red on the Event Report. However, since no data field are required for downgraded these trees, it would be better if they didn't show up in red...

Basically, Downgraded trees on the Event Report should be treated the same way as Dead Fallen trees (for which we don't collect information, other than status).

**Comment by blcampbell** [comment]
@lizmatthews03 
What is the tag status & tree status of a "downgraded" tree?

**Comment by lizmatthews03** [comment]
The tree status is "downgraded to non-sampled" and the tag status should be
"Inactive in field"

-----------------------------
Liz Matthews, PhD
Botanist
National Capital Region Network
Inventory and Monitoring
National Park Service
*https://www.nps.gov/im/ncrn/index.htm
<https://www.nps.gov/im/ncrn/index.htm>*
email: elizabeth_matthews@nps.gov
office: 202-339-8303
cell: 828-337-2946
