### ISSUE TITLE
Event Report-- Remove red highlight from "no tree conditions" on dead trees

### ISSUE THREAD

**Issue by lizmatthews03** [NCRN/ForestVeg#53]
Currently, "no tree conditions" shows up in red highlight on dead trees, when this is really ok (we don't collect conditions on dead trees, other than EAB-infected ash trees).

**Comment by blcampbell** [comment]
"No Tree Conditions"  notice will now appear under the following conditions:

- When no tree condition data is recorded
_**AND**_
- Tree status is not "Dead" (_first 4 letters_)
- Tree status is not "Non-Sampled" (_last 11 letters_)

**Examples (tags & locations omitted)**

![image](https://user-images.githubusercontent.com/36767405/40308904-b572c65e-5cd5-11e8-87e1-98d5457629d0.png)

_See also #51 for highlighting changes (background set to light yellow & red highlights removed)_
