### ISSUE TITLE
"No Tree Conditions" red bar is now showing up on all living trees without tree conditions selected

### ISSUE THREAD

**Issue by lizmatthews03** [NCRN/ForestVeg#64]
After one of the recent DB updates, the "No Tree Conditions" red banner on the Event Report is now showing up on many tree that it previously did not. It now shows up for living trees with the V-C-F check boxes complete. Having no tree conditions is not an error, if the boxes are checked. 

This red banner was previously working correctly for living trees, so I'm not sure what changed.

I have example Event Reports (from the same plot, but printed at different times-- an therefore using different version of the DB) that illustrate the issue...

**Comment by blcampbell** [comment]
@johnpauls or @abrolis please confirm this is what we should see for alive & dead per @lizmatthews03  comments above:

![image](https://user-images.githubusercontent.com/36767405/47446572-83692e80-d789-11e8-9f4b-c80ac38a7bfa.png)

In this case no live trees have the red bar as those w/o tree conditions have V-C-F checkboxes checked.
Should there be an instance where one of the V-C-F checkboxes was unchecked for a live tree and no tree conditions were noted (listed), that would display the NO TREE CONDITIONS in red.

**Comment by abrolis** [comment]
If a tree is alive we should always have those three boxes checked if we've collected all the data.  For dead individuals, the only time we would not leave all the boxes un-checked is if there was a condition of EAB.  Other than that, everything looks good to me.

**Comment by johnpauls** [comment]
@blcampbell , @abrolis 

The sample above is what I would expect to see. If  any of the V C F boxes is unchecked, then there should be a big red bar indicating that happened, regardless of what conditions have been listed. Perhaps the text could be "Vines, Conditions or Foliar Conditions Missing" or something similar.
