### ISSUE TITLE
Sapling foliar conditions don't show up on Event Report

### ISSUE THREAD

**Issue by lizmatthews03** [NCRN/ForestVeg#65]
Not high priority, but impossible to review these data on the event report as currently implemented. Should show up in Sapling Conditions summary area (or similar to how it shows up for trees, under a "foliage conditions" header).

**Comment by blcampbell** [comment]
Sapling foliar conditions added to report with similar functionality to Tree foliar conditions

![image](https://user-images.githubusercontent.com/36767405/47448643-89add980-d78e-11e8-9849-44ab7d2ea06c.png)
