### ISSUE TITLE
Target herb percent cover auto-filling to 0 after the taxon is input

### ISSUE THREAD

**Issue by abrolis** [NCRN/ForestVeg#69]
Target herb % cover auto filling to 0 and no longer highlighted red after the taxon is input.  It does show highlighted red in event report if no percent is entered.  The reason this is an issue for us is that often times we will add targeted herbs without giving a percent when we start monitoring a quad and will only give percents later.

**Comment by blcampbell** [comment]
Appears related to #121. Reopening & will close both when issues is fully addressed.

Default value (0) lies in back-end field definition.
