### ISSUE TITLE
Missing tree/sapling/shrub ID does not show up in highlight on event report

### ISSUE THREAD

**Issue by lizmatthews03** [NCRN/ForestVeg#75]
Missing IDs should be highlighted in some way so that they aren't overlooked during Event Report review in the field.

**Comment by blcampbell** [comment]
Genus and Latin names which are missing will be highlighted as below

![image](https://user-images.githubusercontent.com/36767405/47450671-d5af4d00-d793-11e8-8be0-04891d329226.png)
