### ISSUE TITLE
Tag Summary - Display ALL Tags vs. Active Tags

### ISSUE THREAD

**Issue by blcampbell** [NCRN/ForestVeg#78]
Drop-down listbox displays only active tags.

![image](https://user-images.githubusercontent.com/36767405/46152215-8fbba380-c23e-11e8-8adc-30da819bea80.png)

Problematic for field crew when tracking down individual tag issues.

Consider adding coloration (red?) as a visual cue for inactive tags.
Radio button considered for Active vs. All tags in the dropdown; however this is considered unnecessary as fieldcrew are typically not interested in Active tags only when tracking down issues.

**Comment by johnpauls** [comment]
Just as background - the crew might need this if they find a tag on the forest floor that was lost years ago and the corresponding tree has since been retagged. By allowing the crew to search for inactive tags they will easily be able to figure out what occurred.
