### ISSUE TITLE
Event Report - Add Unsampled Tags

### ISSUE THREAD

**Issue by blcampbell** [NCRN/ForestVeg#8]
Add a section to list the unsampled tags for the event.

**Comment by lizmatthews03** [comment]
Just found another example of this, where an unsampled tree tag didn't show up in the Event Report and simply wasn't sampled this year. See tag 9456 at MANA-0223

**Comment by blcampbell** [comment]
@lizmatthews03 
What is the preferred location for the list of unsampled tags for the event?

1.  **Separate section @ end** of current report that includes both trees & saplings as 2 columns listing same info as Unsampled Tags dropdown (Tag, Class, Azi_Dist, MP)

2.  **Subsections of tree and sapling sections** of the overall report - same info listed as in (1)

3.  Separate section @ end of current report that is a **hybrid listing** trees & saplings in a single column

Any of the 3 is possible. 

Pros/cons - (1)  likely keeps report shortest given it includes 2 columns side-by-side
                   All will identify tag class, but it depends more on how it is envisioned for the field crew's workflow.

**Comment by lizmatthews03** [comment]
I lean towards option 1. I like keeping the trees and saplings separate (in
two columns), and I think the unsampled tags are less likely to be
overlooked if they are in their own section (vs. subsections within the
tree and sapling sections).

JP-- what do you think?

-----------------------------
Liz Matthews, PhD
Botanist
National Capital Region Network
Inventory and Monitoring
National Park Service
*https://www.nps.gov/im/ncrn/index.htm
<https://www.nps.gov/im/ncrn/index.htm>*
email: elizabeth_matthews@nps.gov
office: 202-339-8303
cell: 828-337-2946

**Comment by blcampbell** [comment]
@johnpauls  Your thoughts re: position/grouping of the unsampled tag info?

**Comment by blcampbell** [comment]
@lizmatthews03 , @johnpauls 
Looking futher at this - do you want to see _any_ other classes (tree statuses) other than Tree or Sapling in this list?

Thinking tag statuses like 'Retired (In Office)' would not be displayed... Or should they be?

They currently appear in the unsampled tag dropdown.

Or perhaps this is simply that list sorted by tag status (vs. separate columns for trees and saplings).

Thoughts?
