### ISSUE TITLE
Pseudo Event - Conversion to Actual Event

### ISSUE THREAD

**Issue by blcampbell** [NCRN/ForestVeg#92]
Pseudo events are created for plot re-habs for collecting the basic information on rehabs. These create an event with the pseudo event flag set (pseudoevent flag = 1). During the field season these should be converted to actual events (pseudoevent flag = 0). To avoid users creating a new event where a pseudo event exists, the following are needed:

- Create Event button pops up a form listing all prior year (current year - 1 & later) rehab pseudo-events
- If a user chooses one of the pseudo-events
-- pseudo-event flag for the event is changed from 1 to 0
-- event date changes from the pseudo-event date to the current date (date of clicking the link of the pseudo-event)
-- once these changes happen, the event form opens as normal with the prior information collected in the pseudo-event (rehab) displayed and ready for data collection (and changes if needed)
- If a user finds no applicable pseudo-event, a link will take them to the normal create event form

Considerations:

- When the pseudo-event list appears, it will likely need to be filterable by park to avoid a long list for the user
- Recommend that this filtering be a simple dropdown choice of park at the top of the pseudo-event list form

**Comment by blcampbell** [comment]
@abrolis , @johnpauls  - Confirm/adjust/amplify on the functionality as described above

**Comment by johnpauls** [comment]
Sounds good. If someone accidentally chooses the wrong event, there should be some way to make sure its stays as a pseudo-event.
