### ISSUE TITLE
Add Berberis bealei to plants table

### ISSUE THREAD

**Issue by lizmatthews03** [NCRN/ForestVeg#99]
Previously recognized name was _Mahonia bealei_, but the whole genus of _Mahonia_ has been moved to _Berberis_.

The record of Mahonia spp. at NACE-0399 (2018) should be updated to the new taxon.

**Comment by blcampbell** [comment]
@lizmatthews03 

Currently we have 2 _Mahonia_ records in the plants table - _Mahonia spp._ and _Mahonia aquifolium_

Assuming these two plants table records _(spp. & aquifolium)_ would be adjusted to the new Genus _Berberis_ ...

Several questions:

- Should the order & family remain _Ranunculales_ & _Berberidaceae_ respectively?
- For the new plant record for _Berberis bealei_ (to be added) we'll need these
-- TSN (is there an "accepted TSN")
--  order & family (if different from _Ranunculales_ & _Berberidaceae_ respectively)
-- woody shrub as the other two?
-- common name
-- should it be a 'favorite' in the application?
-- plant code

Above I'm assuming that we'd simply swap out the old genus for the new in the plants table, however it begs the question - Should we be tracking these types of taxon changes?

A swapout would have the effect of changing all existing monitoring records that noted either _Mahonia spp._ or _Mahonia aquifolium_ to the respective _Berberis spp._ or _Berberis aquifolium_ depending on the TSN selected in the monitoring record.

This matters **IF** we need to know that the species taxonomy was the old vs. new taxonomy. There are some complexities to tracking changes as a TSN values are used to identify species and likely the "new" taxonomy would have the same TSN as the old. 

OTOH taxon change tracking could be a simpler solution of a separate table with TSN, original value, changed value, date of change, reason for change (or similar); where the updates are done at the same time as the SQL db script run to implement a plant record change from one genus to another (or similar change).

Of course if we don't need to track the changes, that is easier. However going back to identify which monitoring records used the old genus would not be possible.

Implementing taxon tracking in the shortened 2019 pre-season is unlikely, however the seed of discussion would be planted for a future solution.

**Comment by blcampbell** [comment]
@lizmatthews03 

Reviewing the I&M minimum implementation standards indicates we should be addressing taxonomic references per TSN (issues #100, #101). So references for plant records are needed (see #101) - both existing & new as in the case of _Berberis bealei_.

**Comment by lizmatthews03** [comment]
A few thoughts:

   - For *Berberis bealei*...the order and family should remain the same as
   Mahonia.
      - TSN=509499
      - yep, I'd call it a woody shrub
      - common name=Beale's barberry
      - I suppose it should be a favorite-- *I'll ask **Andrejs if he has **any
      thoughts on this. It's definitely becoming more common in the DC-area
      sites, although I don't think we've actually detected it
frequently in the
      monitoring yet!\*
      - I'm not sure what the "plant code" is...
   - on tracking taxon changes -- to be on the safe side, we should track
   these. Species concepts change over time (e.g., a single taxon becomes two
   taxa), and we may need to track these changes in order to translate our
   current taxonomy to "old" taxonomy
   - we had a discussion via email about the taxonomic references for I&M
   databases this past Spring. I'll forward that to Bonnie and Andrejs, and we
   can discuss it during our forest veg Db meeting on Thursday!

-----------------------------
Liz Matthews, PhD
Botanist
National Capital Region Network
Inventory and Monitoring
National Park Service
*https://www.nps.gov/im/ncrn/index.htm
<https://www.nps.gov/im/ncrn/index.htm>*
email: elizabeth_matthews@nps.gov
office: 202-339-8303
cell: 828-337-2946

**Comment by blcampbell** [comment]
Following up:
Per database field definition PLANTS_Code is the USDA code for the plant. _Berberis bealei_ has the code _BEBE2_ (if it were _Mahonia bealei_ it would be _MABE2_.
